#################################################
#            HubCore Configuration              #
#         Discord: discord.me/esdevelopment     #
#################################################


ITEM:
  SERVER_SELECTOR:
    MATERIAL: BOOK
    SLOT: 4
    NAME: "&6Servers"
  ENDER_BUTT:
    MATERIAL: ENDER_PEARL
    SLOT: 3
    NAME: "&bEnderButt"
    SOUND: "PORTAL"

GLASS_PANE:
  MATERIAL: STAINED_GLASS_PANE
  NAME: " "
  AMOUNT: 1
  VALUE: 15

###
SETTINGS:
  ALWAYS_SUNNY: true
  PING_MESSAGE: "&cYour ping: &f{ping}"
  FLY_ENABLED: "&7[&c!&7] &aFlight has been enabled."
  FLY_DISABLED: "&7[&c!&7] &cFlight has been disabled."

## MEDIA LINKS
MEDIA_LINKS:
  WEBSITE: "&7&l%bullet_point% &aWebsite: &fwww.server.com"
  DISCORD: "&7&l%bullet_point% &aDiscord: &fdiscord.gg/server"
  STORE: "&7&l%bullet_point% &aStore: &fstore.server.com"

## WELCOME MESSAGE (PAPI SUPPORTED)
WELCOME_MESSAGE:
  - "&7&m---------------------------------------"
  - ""
  - "&fWelcome to the &a&lServer!"
  - ""
  - "&7&l%bullet_point% &aStore: &fstore.server.com"
  - "&7&l%bullet_point% &aDiscord: &fdiscord.gg/server"
  - "&7&l%bullet_point% &aTwitter: &ftwitter.com/server"
  - ""
  - "&7&m---------------------------------------"

## SELECTOR CONFIGURATION (PAPI SUPPORTED)
SERVER_SELECTOR:
  SIZE: 27
  NAME: "&7Servers"
  SERVERS:
    1:
      SERVER: server
      MATERIAL: TNT
      SLOT: 13
      NAME: "&6&lServer"
      LORE:
        - ""
        - "&7&l%bullet_point% &a&lServer"
        - ""
        - "&7%right_arrow% &fClick to join &7%right_arrow%"

## SCOREBOARD CONFIGURATION (PAPI SUPPORTED)

SCOREBOARD:
  TITLE: "&4&lServer &fHub"
  LINES:
    - "&7&m-------------------"
    - "&cOnline"
    - "{online}"
    - ""
    - "&cPing: &f{ping}"
    - ""
    - "&7&ostore.server.com"
    - "&7&m-------------------"

# Spawn Configuration
Spawn:
  send:
    message: "&aSending you to spawn"
    sound: "PORTAL"
  void:
    enable: true
    message: "&aSending you to spawn"
