name: HubCore
version: ${project.version}
main: com.esdevelopment.hubcore.HubCore
author: [SaifSharof]
description: HubCore for your server!
softdepend: [PlaceholderAPI]
commands:
  hubreload:
    description: Reloads hubcore's config.yml
  setspawn:
    description: Set's the spawn
  spawn:
    description: Teleports you to the set spawn.
  website:
    description: Sends the server's website
  store:
    description: Sends the server's store
  discord:
    description: Sends the server's discord
permissions:
  hub.command.place:
    description: Allows you to place blocks
  hub.command.break:
    description: Allows you to break blocks
  hubcore.media:
    description: Allows you to have access to all media commands (E.G /discord)
  hubcore.reload:
    description: Allows you to reload hubcore's files.
  hubcore.setspawn:
    description: Allows you to /setspawn
  hubcore.spawn:
    description: Allows you to teleport to spawn

